# Generated by Django 4.2.4 on 2023-08-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderListData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PayTerms', models.CharField(max_length=200, verbose_name='支払条件')),
                ('Status', models.CharField(max_length=200, verbose_name='ステータス')),
                ('Supplier', models.CharField(max_length=200, verbose_name='発注先')),
                ('WorkName', models.CharField(max_length=200, verbose_name='作品名')),
                ('NumberEp', models.IntegerField(default=0, verbose_name='話数')),
                ('OrderDate', models.DateField(max_length=200, verbose_name='発注日')),
                ('Money', models.IntegerField(max_length=200, verbose_name='金額')),
            ],
        ),
    ]
