# Generated by Django 4.2.4 on 2023-08-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prograce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlistdata',
            name='Money',
            field=models.IntegerField(default=0, verbose_name='金額'),
        ),
    ]
