# Generated by Django 4.2.4 on 2023-08-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prograce', '0002_alter_orderlistdata_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberEpListData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(default=0, verbose_name='話数コード')),
                ('Name', models.CharField(max_length=200, verbose_name='話数名')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(default=0, verbose_name='発注先コード')),
                ('Name', models.CharField(max_length=200, verbose_name='発注先名')),
            ],
        ),
        migrations.CreateModel(
            name='WorkNameListData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(default=0, verbose_name='作品コード')),
                ('Name', models.CharField(max_length=200, verbose_name='作品名')),
            ],
        ),
    ]
