# Generated by Django 4.2.4 on 2023-08-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prograce', '0003_numbereplistdata_supplierdata_worknamelistdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NumberEpListData',
            new_name='NumberEpData',
        ),
        migrations.RenameModel(
            old_name='WorkNameListData',
            new_name='WorkNameData',
        ),
    ]
